### ISSUE TITLE
How to use your sketch extraction method to process my own dataset 

### ISSUE THREAD

**Issue by GiantKevin** [SerialLain3170/Colorization#15]
Hey SerialLain, I might have to ask a very stupid question. I really want to use your sketch extraction method to process my own dataset, because you used three different methods to extract the line art. But I haven't figured out how to deal with it. If you can give me some guidance, that would be great. Thanks in advance.

**Comment by SerialLain3170** [comment]
Thank you for the issue and I am very sorry for the inconvenience.

In the document, I wrote about three line extraction methods. However, at present, all colorization methods except for `atari_userhint` can deal with only two extraction methods, XDoG and SketchKeras. These colorization methods cannot deal with Sketch simplification method.

In order to use XDoG and SketchKeras, you need to prepare for the directory that contains line arts extracted by SketchKeras before training and you can execute the command line below (e.g. `nohint_pix2pix`). Please refer to README.md in each directory for details.

```
$ python train.py --data_path <DATA_PATH> --sketch_path <SKETCH_PATH>
```

You do not have to concern about XDoG because this method is done while training.

**Comment by GiantKevin** [comment]
Thank you for your reply. I have used SketchKeras to process my dataset.
