### ISSUE TITLE
Hi, when i try to run this project, i encounter a problem

### ISSUE THREAD

**Issue by meiguoofa** [SerialLain3170/Colorization#18]
>   File "/media/admin/b67979d0-c3be-4160-9879-716c4f8ab874/reference_scft-2/hint_processor.py", line 127, in _blend_preprocess
>     blend = cv.addWeighted(xdog_blur, blend, penc_line, (1 - blend), 0)
> cv2.error: OpenCV(4.5.2) /tmp/pip-req-build-gvmai4nm/opencv/modules/core/src/arithm.cpp:647: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'arithm_op'

**Comment by meiguoofa** [comment]
It's seems like the ground truth image size and sketch image size not match caused this error

**Comment by SerialLain3170** [comment]
Thank you for the issue and I am very sorry for the late response.

I also think that image size of target image and that of line art do not match. How did you obtain line arts? Did you use SketchKeras?

**Comment by meiguoofa** [comment]
Yeah, I use SketchKeras to extract the  sketch image

**Comment by meiguoofa** [comment]
Do you think the results of your project are close to the results in the paper? the paper is "Reference-Based Sketch Image Colorization using Augmented-Self Reference and Dense Semantic Correspondence"

**Comment by SerialLain3170** [comment]
If you did not change codes in SketchKeras, this tool resizes 512x512 after processing. Therefore, you need to prepare 512x512 dataset in advance or have to modify the code of SketchKeras so that sizes of images in original dataset can match those of line art images by SketchKeras.

I do not think the results of my project are close to the results in the paper because I only borrowed ideas of the paper and did not intend to reproduce the results. More specifically, I borrowed the ideas of augmentations and did not borrow triplet loss proposed in the paper. Hence, the results of my project may be inferior to the results in the paper.

**Comment by meiguoofa** [comment]
Thansks for your reply ! Your reply is very helpful to me！😄

**Comment by codexq123** [comment]
Can I use other sketch methods instead of SketchKeras, like Anime2Sketch.

**Comment by SerialLain3170** [comment]
Of course you can! After you extract line arts from color images in `data_path` using Anime2Sketch, you should put the line arts into `sketch_path`.
