### ISSUE TITLE
How to prepare the dataset for atari_userhint_v2

### ISSUE THREAD

**Issue by Foresiver5555** [SerialLain3170/Colorization#22]
Thank you very much for your help.
I would like to use your program "atari_userhint_v2".
I would like to use your "atari_userhint_v2". You mentioned to prepare the color hint image extracted by superpixel in "SS_PATH", but I would like to know more about this.
I would appreciate some guidance on how to prepare them and what the extracted images look like.

**Comment by SerialLain3170** [comment]
Thank you for the issue, and I am sorry for the inconvenience.

Actually, as you can see `IllustDataset` in `dataset.py`, superpixel images in `SS_PATH` are not used even though argument about `SS_PATH` exists. Tentatively, you need to modify `IllustDataset` so that this class can process without superpixel images.

**Comment by SerialLain3170** [comment]
Have you solved?
