### ISSUE TITLE
about atari_userhint_v2's training failed

### ISSUE THREAD

**Issue by microfisher** [SerialLain3170/Colorization#32]
hi, thanks for your time, i use RTX3090 GPU to training atari_userhint_v2, and i put 100 images with color into DATA_PATH and put other 100 images with sketch into  SKETCH_PATH and SS_PATH. then i changed param.yaml like this 
![image](https://user-images.githubusercontent.com/6093582/163353374-27c16a2c-26a0-4ae1-95ab-f26a11a5d8a7.png)

but i got some errors : list out of index / cuda out of memory and etc.. did i do something wrong? thanks

**Comment by SerialLain3170** [comment]
I cannot judge where the error comes from. Could you show the entire error message?

**Comment by 252651980** [comment]
Hi, I notice the parameter 'train.validsize' means the number of pictures for training. If I have 100 picture, I set train.validsize = 100, but it's always OOM. So I think there must be one param that can control the 100 pictures training one by one like a closed loop. Would you please tell me which one is it? Thanks a lot.

**Comment by 252651980** [comment]
I also wonder if you use the training data of [Tagged Anime Illustrations](https://www.kaggle.com/datasets/mylesoneill/tagged-anime-illustrations), how could you set the params dataset.train_size and dataset.valid_size because the pictures' size are not same. Thanks a lot.

**Comment by SerialLain3170** [comment]
Your understanding is not correct about `train.validsize`. `train.validsize` indicates the number of images for visualization to check whether the model would learn in a correct way or not. I recommend that you set the number less than `train.batchsize` or 1 (if your `train.batchsize` is 1). 

I set `dataset.train_size` and `dataset.valid_size` 256 or 224. Since there are discrepancies between sizes of the images in the dataset, I resize them before giving them to the model, and the resizing method solves discrepancies.

@252651980 
I propose that you create another issue if you seemingly have the unrelated question to the issue. By doing that, those who watch the repository would easily reach the issues that are related to their problems afterwards.

**Comment by 252651980** [comment]
> Your understanding is not correct about `train.validsize`. `train.validsize` indicates the number of images for visualization to check whether the model would learn in a correct way or not. I recommend that you set the number less than `train.batchsize` or 1 (if your `train.batchsize` is 1).
> 
> I set `dataset.train_size` and `dataset.valid_size` 256 or 224. Since there are discrepancies between sizes of the images in the dataset, I resize them before giving them to the model, and the resizing method solves discrepancies.
> 
> @252651980 I propose that you create another issue if you seemingly have the unrelated question to the issue. By doing that, those who watch the repository would easily reach the issues that are related to their problems afterwards.

Thanks again. I will continue studying it.
