### ISSUE TITLE
Questions about Adeleine's input

### ISSUE THREAD

**Issue by zxiangwei** [SerialLain3170/Colorization#33]
Hi, I'm sorry, I would like to ask some questions about Adeleine's specific code. I'm not quite sure what the variables point and place mean in server.py. 
![image](https://user-images.githubusercontent.com/44313751/165026607-145c2978-3297-45cf-8b48-ffab039cd126.png)

Also, I noticed that the input of the model is three parameters: line, mask, exist. Can the input of the model be just a picture?
![image](https://user-images.githubusercontent.com/44313751/165026571-e6ccfa71-019d-4701-a1d6-f25d25a4fa3f.png)

**Comment by SerialLain3170** [comment]
Thank you for the issue. 

The colorization model requires three inputs. The visualization for them is the figure below.
- Line art
- Point hint
- Point location: The map indicating the locations of the point hints

![Screen Shot 2022-04-26 at 20 37 08](https://user-images.githubusercontent.com/32360147/165291694-fd307dd2-c19f-4b48-a8a7-619feb772028.png)

When it comes to the first question, `point` corresponds to the point hint and `place` corresponds to the point location. As for the second question, `mask` corresponds to the point hint and `exist` corresponds to the point location. So, these three inputs are images. I am sorry for confusing you.

**Comment by zxiangwei** [comment]
Thank you for your reply and sorry for my late reply. I still have some questions to ask you. One is that when I use auto color without point, I noticed that most of the pictures are a single color (like green), why is this?
![image](https://user-images.githubusercontent.com/44313751/166099004-20303018-7ca7-4442-b6c2-d9663377130a.png)

The second is that I use the cv.write() function to save the image output by the model, but I found that some colors (such as red, blue) are wrong (although the display on the web page is correct), why is this?
line:
![image](https://user-images.githubusercontent.com/44313751/166105057-f3278a9a-f718-4616-85d9-81bb0fa5389e.png)
point：
![image](https://user-images.githubusercontent.com/44313751/166105027-28e82ad1-3fc6-4594-b0f7-b21f4525f712.png)
place:
![image](https://user-images.githubusercontent.com/44313751/166105044-3216edd8-e963-4f1b-aab4-e801b9c66c4f.png)
result:
![image](https://user-images.githubusercontent.com/44313751/166105051-888ec5d9-4738-4b6e-9942-b175f31a0e1b.png)

**Comment by SerialLain3170** [comment]
- As for the 1st question, without hints, I think that the trained model had learnt to generate the statistically plausible color depending on the region. Since the dataset mostly contain white backgrounds, the model seems to predict white color on backgrounds. Also, the model seems to predict skin color on the face because the face is mostly colored with skin color. Aside from these specific regions, the dataset may have many images that contain greenish colors. Therefore, since the model judges the greenish color as the statistically plausible color, it may tend to predict greenish color. 
- When it comes to 2nd question, the color space OpenCV can deal with is different from that of the model output. While OpenCV can deal with BGR as a color space, the model output is in RGB. Hence, in the case of using OpenCV, you can save the image file in a correct color space after converting RGB into BGR.

**Comment by zxiangwei** [comment]
Sorry for the late reply, thank you very much for your reply, your patience and specific answer have helped me tremendously. Also, I would like to ask what network is used by the models in this project? Is it pix2pix or bicyclegan or something else, or which piece of references in the readme can I learn more about?
Thanks again for your help!

**Comment by SerialLain3170** [comment]
In Adeleine, I use `atari_userhint_v2` as the point-based colorization model and `reference_scft` as the reference-based colorization model.

**Comment by zxiangwei** [comment]
Thank you very much for your help！
