### ISSUE TITLE
Model mismatch

### ISSUE THREAD

**Issue by TuesdayHu** [SerialLain3170/Colorization#38]
Hello Lain, thanks a lot for your great work! I'm a beginner in AI and am studying your reference_adain method.
I noticed that the model structure for training(Colorization\reference_adain) is different from the one to be loaded(Colorization\Adeleine\reference). Thus I get a size mismatch error when loading state_dict, and cannot go on to test the trained model.
Is the model correct? Or maybe I need to change the running command? Hope you could help me work out this problem, thank you!

**Comment by SerialLain3170** [comment]
Hi, 

I am sorry for the late reply. The model structure in `reference_adain` is different from the model in `Adeleine/reference` because the latter is based on `reference_scft`. If you would like to use Adeleine using the model structure of `reference_adain`, you need to modify the source codes in Adeleine for matching.

**Comment by TuesdayHu** [comment]
I see, thank you for the instruct!
